# Schema for the accessibility module configuration.
accessibility.settings:
  type: config_object
  label: 'Accessibility settings'
  mapping:
    # Existing settings
    api_key:
      type: string
      label: 'API Key'
    debug_mode:
      type: boolean
      label: 'Debug mode'
    show_widget:
      type: boolean
      label: 'Show widget'
    widget_position:
      type: string
      label: 'Widget position'
    
    # LLM Settings
    llm_enabled:
      type: boolean
      label: 'Enable LLM Analysis'
    llm_provider:
      type: string
      label: 'LLM Provider'
    llm_model:
      type: string
      label: 'LLM Model'
    llm_temperature:
      type: float
      label: 'Temperature (0-1)'
    llm_max_tokens:
      type: integer
      label: 'Max Tokens'
    llm_cache_ttl:
      type: integer
      label: 'Cache TTL (seconds)'
